all:
  vars: 
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_retries: 10
    ansible_user: root
    ansible_password: 3tango
  hosts:
    host1: 
      ansible_host: 10.237.157.75
    host2: 
      ansible_host: 10.237.157.74
    

