- name: connect to two machines, send ping traffic from machine 1 to machine 2 
  hosts: host1
  become: true
  tasks:
  - name: ping host2
    ansible.builtin.shell: ping -w 5 {{ hostvars['host2']['ansible_host']}} 
    register: log_content